name: Build
on:
  push:
    tags-ignore:
      - v**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
