name: Release
on:
  push:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and publish to Curseforge & Modrinth
        run: ./gradlew curseforge modrinth --stacktrace
        env:
          CURSE_API_KEY: ${{ secrets.CF_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Get changelog for Github release
        id: changelog
        run: echo "::set-output name=changes::$(./gradlew getChangelog --no-header --console=plain -q)"
      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{ steps.changelog.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
